export const TESTIMONIALS = [
    {
        id: "t1",
        quote: "LetterLab is hands down the best tool I’ve found for replying to long, confusing email threads. It pulls exactly what I need and drafts the perfect response in seconds.",
        name: "Jessica M.",
        title: "Project Manager",
        company: "Acme Corp",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Management",
    },
    {
        id: "t2",
        quote: "As a student, emailing professors used to stress me out. Now, I just click a button, and my reply sounds professional, polite, and completely accurate to the thread.",
        name: "David R.",
        title: "College Senior",
        company: "State University",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Education",
    },
    {
        id: "t3",
        quote: "What I love most is how much time it saves me. I don’t have to re-read entire chains to know what’s going on. The context-pulling feature is an absolute game-changer.",
        name: "Sarah L.",
        title: "Operations Director",
        company: "Global Logistics",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Operations",
    }
];
