export const TESTIMONIALS = [
    {
        id: "t1",
        quote: "LetterLab is hands down the best tool I’ve found for replying to long, confusing email threads. It pulls exactly what I need and drafts the perfect response in seconds.",
        name: "Pratik Thapa",
        title: "Student",
        company: "McNeese State University",
        rating: 4,
        avatarUrl: null,
        verified: true,
        tag: "Civil Engineering",
    },
    {
        id: "t2",
        quote: "As a student, emailing professors used to stress me out. Now, I just click a button, and my reply sounds professional, polite, and completely accurate to the thread.",
        name: "Yogesh Khadka",
        title: "Student",
        company: "McNeese State University",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Civil Engineering",
    },
    {
        id: "t3",
        quote: "What I love most is how much time it saves me. I don’t have to re-read entire chains to know what’s going on. The context-pulling feature is an absolute game-changer.",
        name: "Dipendra Kandel",
        title: "Student",
        company: "McNeese State University",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Mech. Engineering",
    }
];
