
export const TESTIMONIALS = [
    {
        id: "t1",
        quote: "We stopped digging through threads. LetterLab surfaces the context, drafts a clean reply, and keeps our team consistent across customer conversations.",
        name: "Marcus Chen",
        title: "Head of Customer Success",
        company: "Apex Solutions",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Support",
    },
    {
        id: "t2",
        quote: "The summary + suggested reply cuts our follow-ups from minutes to seconds. It feels like having an ops assistant inside Gmail.",
        name: "Sarah Jenkins",
        title: "Operations Lead",
        company: "Midwest Health Group",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Operations",
    },
    {
        id: "t3",
        quote: "Finally, a tool that understands tone. I don't have to rewrite the drafts—they actually sound like me, just more polished.",
        name: "David Ross",
        title: "Senior Account Executive",
        company: "TechFlow Inc.",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Sales",
    },
    {
        id: "t4",
        quote: "Managing student inquiries used to take my whole morning. Now I clear my inbox in 20 minutes without sacrificing quality.",
        name: "Dr. Emily Carter",
        title: "Department Chair",
        company: "State University",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Education",
    },
    {
        id: "t5",
        quote: "It captures the nuance of complex negotiations perfectly. The context pulling feature is a game changer for long email chains.",
        name: "James Wilson",
        title: "Legal Counsel",
        company: "Wilson & Partners",
        rating: 4,
        avatarUrl: null,
        verified: true,
        tag: "Legal",
    },
    {
        id: "t6",
        quote: "Our response time dropped by 40% in the first week. The AI doesn't just guess; it actually reads the history.",
        name: "Olivia Martinez",
        title: "Support Manager",
        company: "CloudScale",
        rating: 5,
        avatarUrl: null,
        verified: true,
        tag: "Support",
    }
];
