
import React from 'react';
import { motion } from 'framer-motion';
import { Box, Container, Typography, Stack, Paper, Divider, Grid } from '@mui/material';
import AssignmentIcon from '@mui/icons-material/Assignment';
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser';
import WarningIcon from '@mui/icons-material/Warning';

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
};

export default function TermsPage() {
    const sections = [
        {
            id: "acceptance",
            title: "1. Acceptance of Terms",
            content: "By using LetterLab Pro, you agree to these terms. If you do not agree, please do not use our services."
        },
        {
            id: "usage",
            title: "2. Permitted Use",
            content: "You are granted a non-exclusive license to use our drafting tools for professional communication. Automated scraping or reverse engineering is strictly prohibited."
        },
        {
            id: "liability",
            title: "3. Limitation of Liability",
            content: "LetterLab is provided 'as is'. We are not liable for any damages arising from your use of the platform, service interruptions, or the specific outputs generated by AI engines."
        }
    ];

    return (
        <Box sx={{ pb: 10 }}>
            {/* Premium Hero */}
            <Box sx={{
                pt: { xs: 8, md: 12 },
                pb: { xs: 6, md: 8 },
                bgcolor: 'action.hover',
                borderBottom: '1px solid',
                borderColor: 'divider'
            }}>
                <Container maxWidth="lg">
                    <Grid container spacing={6} alignItems="center">
                        <Grid item xs={12} md={7}>
                            <Stack spacing={3}>
                                <Typography variant="caption" sx={{ textTransform: 'uppercase', letterSpacing: '0.2em', fontWeight: 800, color: 'primary.main' }}>
                                    Legal · Guidelines
                                </Typography>
                                <Typography variant="h1" sx={{ fontSize: { xs: '32px', md: '48px' }, fontWeight: 800 }}>
                                    Terms of Service
                                </Typography>
                                <Typography variant="body1" sx={{ color: 'text.secondary', fontSize: '18px', maxWidth: 600 }}>
                                    Please read our terms of service carefully. They govern your use of the LetterLab Pro platform and its AI companion tools.
                                </Typography>
                            </Stack>
                        </Grid>
                        <Grid item xs={12} md={5}>
                            <Paper sx={{ p: 3, borderRadius: 4, display: 'flex', flexDirection: 'column', gap: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 800 }}>Key Terms</Typography>
                                {[
                                    { icon: <AssignmentIcon fontSize="small" color="primary" />, text: "One account per user." },
                                    { icon: <VerifiedUserIcon fontSize="small" color="primary" />, text: "You own your generated drafts." },
                                    { icon: <WarningIcon fontSize="small" color="primary" />, text: "No misuse of AI engines." }
                                ].map((item, i) => (
                                    <Stack key={i} direction="row" spacing={2} alignItems="center">
                                        {item.icon}
                                        <Typography variant="body2" sx={{ fontWeight: 500 }}>{item.text}</Typography>
                                    </Stack>
                                ))}
                            </Paper>
                        </Grid>
                    </Grid>
                </Container>
            </Box>

            {/* Main Content */}
            <Container maxWidth="lg" sx={{ mt: 8 }}>
                <Grid container spacing={8}>
                    {/* ToC Sidebar */}
                    <Grid item xs={12} md={3} sx={{ display: { xs: 'none', md: 'block' } }}>
                        <Box sx={{ position: 'sticky', top: 100 }}>
                            <Typography variant="overline" sx={{ fontWeight: 800, color: 'text.disabled' }}>Contents</Typography>
                            <Stack spacing={1} sx={{ mt: 2 }}>
                                {sections.map(s => (
                                    <Typography
                                        key={s.id}
                                        component="a"
                                        href={`#${s.id}`}
                                        sx={{
                                            fontSize: '14px',
                                            fontWeight: 500,
                                            color: 'text.secondary',
                                            textDecoration: 'none',
                                            '&:hover': { color: 'primary.main' }
                                        }}
                                    >
                                        {s.title}
                                    </Typography>
                                ))}
                            </Stack>
                        </Box>
                    </Grid>

                    {/* Text Content */}
                    <Grid item xs={12} md={9}>
                        <Stack spacing={6}>
                            {sections.map(s => (
                                <Box key={s.id} id={s.id} component={motion.div} variants={itemVariants} initial="hidden" whileInView="visible" viewport={{ once: true }}>
                                    <Typography variant="h5" sx={{ fontWeight: 800, mb: 2 }}>{s.title}</Typography>
                                    <Typography variant="body1" sx={{ color: 'text.secondary', lineHeight: 1.8 }}>
                                        {s.content}
                                    </Typography>
                                    <Divider sx={{ mt: 4 }} />
                                </Box>
                            ))}
                        </Stack>
                    </Grid>
                </Grid>
            </Container>
        </Box>
    );
}
